name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    strategy:
      matrix:
        target:
          - target: x86_64-unknown-linux-gnu
            strip: strip
          - target: x86_64-unknown-linux-musl
            strip: strip
            extra: --static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.target }}
      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target.target }}
          ${{ matrix.target.strip }} target/${{ matrix.target.target }}/release/lifeos
          gzip -k -f target/${{ matrix.target.target }}/release/lifeos
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/${{ matrix.target.target }}/release/lifeos
            target/${{ matrix.target.target }}/release/lifeos.gz